//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RehberUygulaması {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RehberUygulaması.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string AddBtn {
            get {
                return ResourceManager.GetString("AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        internal static string BackBtn {
            get {
                return ResourceManager.GetString("BackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string DeleteBtn {
            get {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölümler.
        /// </summary>
        internal static string DepartmentAddBtn {
            get {
                return ResourceManager.GetString("DepartmentAddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departman Adı.
        /// </summary>
        internal static string DepartmentAddLbl {
            get {
                return ResourceManager.GetString("DepartmentAddLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölümü.
        /// </summary>
        internal static string DepartmentLbl {
            get {
                return ResourceManager.GetString("DepartmentLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string EmailLbl {
            get {
                return ResourceManager.GetString("EmailLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        internal static string FirstNameLbl {
            get {
                return ResourceManager.GetString("FirstNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvanlar.
        /// </summary>
        internal static string JobTitleAddBtn {
            get {
                return ResourceManager.GetString("JobTitleAddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soy Adı.
        /// </summary>
        internal static string LastNameLbl {
            get {
                return ResourceManager.GetString("LastNameLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numara.
        /// </summary>
        internal static string NumberLbl {
            get {
                return ResourceManager.GetString("NumberLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişi Ekle.
        /// </summary>
        internal static string PersonAddBtn {
            get {
                return ResourceManager.GetString("PersonAddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        internal static string PersonUpdateBtn {
            get {
                return ResourceManager.GetString("PersonUpdateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        internal static string SearchLbl {
            get {
                return ResourceManager.GetString("SearchLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvanı.
        /// </summary>
        internal static string TitleAddLbl {
            get {
                return ResourceManager.GetString("TitleAddLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvan.
        /// </summary>
        internal static string TitleLbl {
            get {
                return ResourceManager.GetString("TitleLbl", resourceCulture);
            }
        }
    }
}
